terraform {
  backend "s3" {
    bucket         = "tofu-state-notifycal-layer-0"
    dynamodb_table = "tofu-lock-notifycal-layer-0"
    encrypt        = true
    key            = "ci/terraform.tfstate"
    region         = "eu-west-1"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "aws_region" {
  type = string
}

variable "project" {
  type = string
}

variable "stack" {
  type = string
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project = var.project
      Region = var.aws_region
      Managed-By = "Terragrunt"
      Stack = var.stack
    }
  }
}

provider "github" {
  owner = var.github_organization_name
}
